name: test

on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: make directory
        run: mkdir level1
      - name: cd into directory and output working directory
        run:  | 
              cd level1
              pwd
      - name: output working directory
        run: pwd 
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job 2 output working directory 
        run: pwd 

