name: test

on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: job 1 step 1
        run: mkdir level1
      - name: job 1 step 2
        run:  cd level1
              pwd
      - name: job 1 step 3
        run: pwd 
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job 2 step 1
        run: a = pwd 

